// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSBtyKCQHHbmtkxP50euoaHG1FGKts4ik',
    appId: '1:532231020344:web:52ec1e2ba0643847486bcd',
    messagingSenderId: '532231020344',
    projectId: 'gai-sangma',
    authDomain: 'gai-sangma.firebaseapp.com',
    storageBucket: 'gai-sangma.firebasestorage.app',
    measurementId: 'G-GRDSFFSK84',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtCt03YPKR3v6k3L3ymNQLK-dDP4_ZveA',
    appId: '1:532231020344:android:9d7b1c29a458a8ac486bcd',
    messagingSenderId: '532231020344',
    projectId: 'gai-sangma',
    storageBucket: 'gai-sangma.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrM4gyyKv4wREnWkHPQCGWCxvuBOkxCH4',
    appId: '1:532231020344:ios:6c4a6f4b91411d40486bcd',
    messagingSenderId: '532231020344',
    projectId: 'gai-sangma',
    storageBucket: 'gai-sangma.firebasestorage.app',
    androidClientId: '532231020344-capj96po98o89hids2n5fkgmsp17cbh1.apps.googleusercontent.com',
    iosClientId: '532231020344-ef5oba0ede5ss2a0issgjmee9pd0cf2p.apps.googleusercontent.com',
    iosBundleId: 'com.example.smm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrM4gyyKv4wREnWkHPQCGWCxvuBOkxCH4',
    appId: '1:532231020344:ios:6c4a6f4b91411d40486bcd',
    messagingSenderId: '532231020344',
    projectId: 'gai-sangma',
    storageBucket: 'gai-sangma.firebasestorage.app',
    androidClientId: '532231020344-capj96po98o89hids2n5fkgmsp17cbh1.apps.googleusercontent.com',
    iosClientId: '532231020344-ef5oba0ede5ss2a0issgjmee9pd0cf2p.apps.googleusercontent.com',
    iosBundleId: 'com.example.smm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSBtyKCQHHbmtkxP50euoaHG1FGKts4ik',
    appId: '1:532231020344:web:c3d2484d86aa9c42486bcd',
    messagingSenderId: '532231020344',
    projectId: 'gai-sangma',
    authDomain: 'gai-sangma.firebaseapp.com',
    storageBucket: 'gai-sangma.firebasestorage.app',
    measurementId: 'G-HENHD64Z7Z',
  );
}
